version: '2'
services:
  service:
    image: my/node-compose-service.slim
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: redis:4.0-alpine
    ports:
      - "16379:6379"

