version: '2'
services:
  appsvc:
    build: .
    image: my/demo-node-compose-service
    ports:
      - "8008:8000"
    depends_on:
      - redis
  redis:
    image: redis:4.0-alpine
    ports:
      - "16379:6379"


